services:
        buildall:
                image: ubuntu:22.04
                container_name: mubuild
                volumes:
                        - ./:/root/
                restart: "no"
                command: bash /root/scripts/container_setup.sh
                environment: 
                        TZ: Asia/Shanghai
                        DEBIAN_FRONTEND: noninteractive
