# This is a basic workflow to help you get started with Actions

name: Build uefi for all devices.

## Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'Binaries'
      - 'Common/**'
      - 'Features/**'
      - 'MU_BASECORE'
      - 'Silicon/Arm/**'
      - 'scripts/**'
      - 'Platforms/SurfaceDuoFamilyPkg/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow on pull request
  pull_request:
    types: [opened, reopened]
    paths:
      - 'Binaries'
      - 'Common/**'
      - 'Features/**'
      - 'MU_BASECORE'
      - 'Silicon/Arm/**'
      - 'scripts/**'
      - 'Platforms/SurfaceDuoFamilyPkg/**'


# Indicate that we are running in CI
env:
  WM_CI_BUILD: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: build uefi for all devices in all platforms
        run: bash scripts/ci_setup.sh && ./build_uefi.py -p all

      - name: Upload Atoll's Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uefi-images-atoll-sm7125
          path: Build/AtollPkg/ci_artifacts
          compression-level: 9

      - name: Upload Hana's Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uefi-images-hana-sm8150
          path: Build/SurfaceDuo1Pkg/ci_artifacts
          compression-level: 9

      - name: Upload Kona's Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uefi-images-kona-sm8150
          path: Build/KonaPkg/ci_artifacts
          compression-level: 9

      - name: Upload Kodiak's Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uefi-images-kodiak-sm7325
          path: Build/KodiakPkg/ci_artifacts
          compression-level: 9

      - name: Upload Kailua's Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uefi-images-kailua-sm8550
          path: Build/KailuaPkg/ci_artifacts
          compression-level: 9

      - name: Upload Lahaina's Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uefi-images-lahaina-sm8350
          path: Build/SurfaceDuo2Pkg/ci_artifacts
          compression-level: 9
