# This is a basic workflow to help you get started with Actions

name: Build All Silicons

## Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: build uefi for all devices in all silicons
        run: bash scripts/container_setup.sh && ./build_uefi.py -s all

      - name: Upload Hoya's Artifact
        uses: actions/upload-artifact@v3
        with:
          name: uefi-images-hoya
          path: Build/Hoya-AARCH64/*.img

      - name: Upload Atoll's Artifact
        uses: actions/upload-artifact@v3
        with:
          name: uefi-images-atoll
          path: Build/Atoll-AARCH64/*.img

      - name: Upload Hana's Artifact
        uses: actions/upload-artifact@v3
        with:
          name: uefi-images-hana
          path: Build/SurfaceDuo1-AARCH64/*.img

      - name: Upload Kodiak's Artifact
        uses: actions/upload-artifact@v3
        with:
          name: uefi-images-kodiak
          path: Build/Kodiak-AARCH64/*.img

      - name: Upload Kailua's Artifact
        uses: actions/upload-artifact@v3
        with:
          name: uefi-images-kailua
          path: Build/Kailua-AARCH64/*.img
