# This is a basic workflow to help you get started with Actions

name: Build uefi for all SM7125 devices.

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Indicate that we are running in CI
env:
  WM_CI_BUILD: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs called "build" and "package"
  build:
    uses: woa-msmnile/msmnilePkg/.github/workflows/build_platform.yml@main
    with:
      platform: RennellPkg
    secrets: inherit

  package:
    strategy:
      matrix:
        target:
          [
            { platform: "RennellPkg", codename: "rennell", chipname: "sm7125" },
          ]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: Build
          merge-multiple: true

      - name: Upload ${{ matrix.target.codename }}'s Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uefi-images-${{ matrix.target.codename }}-${{ matrix.target.chipname }}
          path: Build/${{ matrix.target.platform }}/ci_artifacts
          compression-level: 9
