# This is a basic workflow to help you get started with Actions

name: Build uefi for all Sm7125 devices.

# Controls when the workflow will run
on:
#  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Indicate that we are running in CI
env:
  WM_CI_BUILD = true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: build uefi for all devices in AtollPkg.
        run: bash scripts/ci_setup.sh && ./build_uefi.py -d all -p Sm7125

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: uefi-images-sm7125
          path: Build/*/ci_artifact
